spring.application.name=product-bundling


spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


api.key=${API_KEY}




http.client.max-connections=300
http.client.max-per-route=100
http.client.connection-request-timeout=20000
http.client.connect-timeout=20000
http.client.read-timeout=20000

server.port=8087
server.address=0.0.0.0

sarinah-portal.base-url=  https://192.168.70.98/api/public
sarinah-portal.product_inj.url =${sarinah-portal.base-url}/product_inj

spring.kafka.bootstrap-servers=10.0.7.32:9092



spring.thymeleaf.prefix= classpath:/templates/
spring.thymeleaf.suffix= .html

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


spring.thymeleaf.cache=false

server.forward-headers-strategy=framework

server.servlet.contextPath=/inventory-injourney
